### ISSUE TITLE
Compile errors on RHEL 7.9

### ISSUE THREAD

**Issue by LordChaos73** [Lusitaniae/apache_exporter#133]
Hi,

I need to compile the go binary on a RHEL 7.9 server which has _no_ internet access. I did the following:

* downloaded the source code on my laptop
* created a Go environment on my laptop
* go get && go mod vendor
* transferred the package to the target server

The binary compiles fine on my laptop (go version go1.18.2 darwin/arm64).

When I try to build the binary on the target server (go version go1.9.4 linux/amd64) I get these errors:

```
# apache_exporter/vendor/github.com/prometheus/client_golang/prometheus
vendor/github.com/prometheus/client_golang/prometheus/go_collector.go:353:15: undefined: debug.ReadBuildInfo
# apache_exporter/vendor/golang.org/x/net/http2
vendor/golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
vendor/golang.org/x/net/http2/server.go:234:72: undefined: tls.VersionTLS13
```

**Comment by LordChaos73** [comment]
I wasn't aware of the existence of the pre-compiled binaries. Issue can be closed.
